spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  session:
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/springblog;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    web:
      pageable:
        one-indexed-parameters: true


springblog:
  jwt-key: "secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey"

