### 로그인


POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=minyeob&password=1234


### 인증 페이지 요청

GET http://localhost:8080/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIn0.yNfvFWtJZuMAHekp1zXHUZgpicAZNAVTBIgmbLIRlDquIzkwo3wIOkZjPI1Z63GBT5oStwEONDTiQq7ksRX34w